pool:
  name: Azure Pipelines
variables:
  AzureTableStorage: 'DefaultEndpointsProtocol=https;AccountName=tablestrg21;AccountKey=aYBTaQIqFVdXTPEKBarbd0U7frkAV9X8plbYhfP6Kg5cL1p34snMxM/5l3l8VJ5KtsqP7vLUju15Rs32IdbPKg==;EndpointSuffix=core.windows.net;'
  AssetsTableName: 'Assets'
  AssetsTypeTableName: 'AssetsTypes1'
  AssetsCategoryTableName: 'AssetsCategories01'
  SecurityKey: '20482048'

steps:
- task: Docker@0
  displayName: 'Build an image'
  env:
    AzureTableStorage: $(AzureTableStorage)
    AssetsTableName: $(AssetsTableName)
    AssetsTypeTableName: $(AssetsTypeTableName)
    AssetsCategoryTableName: $(AssetsCategoryTableName)
    SecurityKey: $(SecurityKey)
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: MSSDockerRegistry
    additionalImageTags: |
     alpha-$(Build.BuildId)
     alpha

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: MSSDockerRegistry
    action: 'Push an image'
    additionalImageTags: |
     alpha-$(Build.BuildId)
     alpha

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: Machine01
    runOptions: inline
    inline: 'sudo docker service update --update-delay=2m --update-monitor=30s --rollback-delay=20s --with-registry-auth --image registry.mss.ba/backend_sanjingolos_assets:alpha assets-api_assets-api'
